# Generated by Django 3.2.9 on 2022-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(default='无', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token_key', models.CharField(default=None, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
